### ISSUE TITLE
azcopy breaks pipeline tasks

### ISSUE THREAD

**Issue by jrudley** [Azure-Samples/jmeter-aci-terraform#58]
AZcopy does not take in account key anymore which breaks the pipeline. I'll eventually get to submitting a PR, but a quick fix is below

`
- task: AzureCLI@2
  displayName: 'SETUP: Transfer JMeter Files to Storage Account'
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptType: 'bash'
    workingDirectory: ./terraform
    scriptLocation: 'inlineScript'
    inlineScript: |
      SHARENAME=$(terraform output storage_file_share_name)
      ACCOUNTNAME=$(terraform output storage_account_name)
      STGKEY=$(terraform output storage_account_key)
      az storage file upload-batch --account-key $STGKEY --account-name $ACCOUNTNAME --destination $SHARENAME --source $(JMETER_DIRECTORY_INPUT)
`

`
- task: AzureCLI@2
  displayName: 'RESULTS: Download Jmeter results'
  inputs:
    azureSubscription: $(AZURE_SERVICE_CONNECTION_NAME)
    scriptType: 'bash'
    workingDirectory: ./terraform
    scriptLocation: 'inlineScript'
    inlineScript: |
      RG=$(terraform output resource_group_name)
      SHARENAME=$(terraform output storage_file_share_name)
      STGKEY=$(terraform output storage_account_key)
      ACCOUNTNAME=$(terraform output storage_account_name)    
      mkdir $(System.DefaultWorkingDirectory)/results
      az storage file download-batch --account-key $STGKEY --account-name $ACCOUNTNAME --destination $(JMETER_DIRECTORY_OUTPUT) --no-progress --source $SHARENAME
`

**Comment by willfell** [comment]
@jrudley I've been trying to find a fix for the past week so this is awesome. Thank you!

Before it's solved for me I am undergoing an issue on the upload portion. 
`ERROR: Client-Request-ID=4d01f112-8060-11eb-bc86-000d3af5de63 Retry policy did not allow for a retry: , HTTP status code=Unknown, Exception=HTTPSConnectionPool(host='%22dvtdevstorage92964a8f%22.file.core.windows.net', port=443): Max retries exceeded with url: /%22dvtdevshare%22/ComplicatedLoad_100.jmx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f44df9f12b0>: Failed to establish a new connection: [Errno -2] Name or service not known',)).
ERROR: HTTPSConnectionPool(host='%22dvtdevstorage92964a8f%22.file.core.windows.net', port=443): Max retries exceeded with url: /%22dvtdevshare%22/ComplicatedLoad_100.jmx (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f44df9f12b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

Would you happen to know what could be causing this?

**Comment by jrudley** [comment]
Hrm, you are using terraform to create the storage account, right? Any
weird characters or spacing issues in your tf variables? Using a hosted
agent pool? After my fix, I've ran pipeline around 20 times today with no
issues.

**Comment by jrudley** [comment]
Here is my pipeline remove the .txt at the end

[azure-pipelines.load-test.yml.txt](https://github.com/Azure-Samples/jmeter-aci-terraform/files/6104784/azure-pipelines.load-test.yml.txt)

**Comment by jrudley** [comment]
[azure-pipelines.load-test.yml (2).txt](https://github.com/Azure-Samples/jmeter-aci-terraform/files/6104800/azure-pipelines.load-test.yml.2.txt)

**Comment by willfell** [comment]
Thanks for uploading the file. Ours is configured the same, using the outputs of the terraform deployment. 
Going to try some things and will come back if I'm able to find a fix.

**Comment by willfell** [comment]
I took out the terraform installer step which is why I was getting that issue. Putting that step back into it resolved the issue and it's now uploading / downloading. 
Thank you again @jrudley !

**Comment by jrudley** [comment]
Cool, glad you got it figured out
